name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          workingDirectory: 'crawler'
          apiToken: ${{ secrets.CF_API_TOKEN }}

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          workingDirectory: 'trigger'
          apiToken: ${{ secrets.CF_API_TOKEN }}